version: '3.7'

services:
  algo:
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./.env:/app/.env:ro
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "host.docker.internal:host-gateway"   # needed on Linux
